name: Canneman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#215d8f'
    - '#ffffff'
    - '#5f93c2'
    - '#89b5e4'
    - '#437498'
  brandStrength: 0.006112422328442335
  lightness: 0.8536720399279147
  saturation: 0.6338950290810317
  rhythmicContrast: 0.4990813711192459
purpose: []
